// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("ServiceStack.Extras.Serilog")]
[assembly: AssemblyCompanyAttribute("Alexey Zimarev")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2016 Alexey Zimarev")]
[assembly: AssemblyVersionAttribute("2.0.1.0")]
[assembly: AssemblyFileVersionAttribute("2.0.1.0")]
[assembly: AssemblyInformationalVersionAttribute("2.0.1+4.Branch.master.Sha.3faf89d572a6c2940c675821af9e70de839fec8a")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.0.1.0";
        internal const string InformationalVersion = "2.0.1+4.Branch.master.Sha.3faf89d572a6c2940c675821af9e70de839fec8a";
    }
}
